
services:
  airflowproject:
    # image: airflowproject:latest
    
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    command: airflow standalone

    environment:
      - AIRFLOW__SMTP__SMTP_HOST=mailhog
      - AIRFLOW__SMTP__SMTP_PORT=1025
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflow@example.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=False
      - AIRFLOW__SMTP__SMTP_SSL=False
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP Port